  ## Playbook to provision and deploy a MySQL Database with the given configurations
---
- name: Deploy Database
  hosts: all
  remote_user: jhone
  become: yes
  tasks:
  - name: Install mysql-server
    apt:
      name: mysql-server
      update_cache: yes
  - name: Copy SQL Scripts
    ansible.builtin.copy:
      src: ../db/
      dest: /home/jhone/db
  - name: Clean DB
    shell:
      cmd: mysql -u root < /home/jhone/db/db-reset.sql
  - name: Run DB creation script
    shell:
      cmd: mysql -u root < /home/jhone/db/table-creation.sql
  - name: Add data
    shell:
      cmd: mysql -u root < /home/jhone/db/data-addition.sql