  ## Playbook to provision and deploy a MySQL Database with the given configurations
---
- name: Deploy Database
  hosts: all
  remote_user: jhone
  become: yes
  tasks:
  - name: Install mysql-server
    apt:
      name: mysql-server
      update_cache: yes
  - name: Copy SQL Scripts
    ansible.builtin.copy:
      src: ../db/
      dest: /home/jhone/db/