name: Backend Deployment Pipeline
on:
    workflow_dispatch:
    push:
        branches:
            - "master"
            #Temp dev config delete later
            - "feature/**"
jobs:
    deploy-infrastructure:
        uses: LabregoPT/movie-analyst-infra/.github/workflows/infra-deploy.yml@master
        secrets:
            aws_access_key: "asd"
            aws_secret_access_key: "asd"
            tf_api_token: "asd"
            gcp_credentials_json: "asd"