name: Backend Deployment Pipeline
on:
    workflow_dispatch:
    push:
        branches:
            - "master"
            #Temp dev config delete later
            - "feature/**"
jobs:
    deploy-infrastructure:
        uses: LabregoPT/movie-analyst-infra/.github/workflows/infra-deploy.yml@master
        secrets:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            tf_api_token: ${{ secrets.TF_API_TOKEN }}
            gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
            