name: Backend CI Pipeline
on:
    workflow_dispatch:
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
            - name: Install packages
              run: |
                npm update
                npm install
            - name: Run tests
              run: |
                sudo systemctl start mysql.service
                sudo mysql --user=root --password=root < "./db/table-creation.sql"
                netstat -tlnp
                npm run test-unit
              env:
                DB_HOST: "localhost"
                DB_USER: "root"
                DB_PASSWORD: "root"
                DB_NAME: "movie_db"